/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DmDTLvY2FML
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

export function Component() {
  return (
    <div className="flex flex-col min-h-[100vh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <IconHammer className="h-6 w-6" />
          <span className="sr-only">Blacksmith Inc</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Welcome to Blacksmith Inc
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  We specialize in custom blacksmithing projects.
                </p>
              </div>
              <Button>Explore</Button>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl/tight">Our Custom Builds</h2>
            <div className="grid gap-6 mt-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              <Card>
                <img
                  alt="Custom Build 1"
                  className="object-cover rounded-t"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold">Custom Build 1</h3>
                  <p className="text-gray-500 dark:text-gray-400">A brief description of the custom build.</p>
                </div>
              </Card>
              <Card>
                <img
                  alt="Custom Build 2"
                  className="object-cover rounded-t"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold">Custom Build 2</h3>
                  <p className="text-gray-500 dark:text-gray-400">A brief description of the custom build.</p>
                </div>
              </Card>
              <Card>
                <img
                  alt="Custom Build 3"
                  className="object-cover rounded-t"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold">Custom Build 3</h3>
                  <p className="text-gray-500 dark:text-gray-400">A brief description of the custom build.</p>
                </div>
              </Card>
              <Card>
                <img
                  alt="Custom Build 4"
                  className="object-cover rounded-t"
                  height="200"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "200/200",
                    objectFit: "cover",
                  }}
                  width="200"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold">Custom Build 4</h3>
                  <p className="text-gray-500 dark:text-gray-400">A brief description of the custom build.</p>
                </div>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl/tight">Contact Us</h2>
            <form className="grid gap-6 mt-6 sm:grid-cols-2">
              <Input placeholder="Your Name" type="text" />
              <Input placeholder="Your Email" type="email" />
              <textarea className="h-36 sm:col-span-2" placeholder="Your Message" />
              <Button className="sm:col-span-2" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© Blacksmith Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function IconHammer(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="m15 12-8.5 8.5c-.83.83-2.17.83-3 0 0 0 0 0 0 0a2.12 2.12 0 0 1 0-3L12 9" />
      <path d="M17.64 15 22 10.64" />
      <path d="m20.91 11.7-1.25-1.25c-.6-.6-.93-1.4-.93-2.25v-.86L16.01 4.6a5.56 5.56 0 0 0-3.94-1.64H9l.92.82A6.18 6.18 0 0 1 12 8.4v1.56l2 2h2.47l2.26 1.91" />
    </svg>
  )
}
