/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lmgStCUvKxS
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold">Submit a Repair Request</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Please provide the necessary details about the repair needed.
        </p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-1 gap-4">
          <div className="space-y-2">
            <Label htmlFor="repair-image">Upload an Image</Label>
            <Input id="repair-image" type="file" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea className="min-h-[100px]" id="description" placeholder="Describe the issue" />
          </div>
        </div>
        <Button type="submit">Submit Request</Button>
      </div>
    </div>
  )
}
